#!/bin/sh

dir="$1"
pipe="$2"

. "$dir/rn-modules"

loop() {
    while true; do
        "$1"
        sleep "$2"
    done > "$pipe" &
}

# Modules that update in intervals
# (loop function seconds)
loop "bat_module" 7
loop "wifi_module" 5
loop "date_module" 1

# Continuously read and sort incoming output from modules
# Sort based on update signal (first char)
# Set the actual status text
while read line; do
    case "$line" in
        B*) bat="${line#?}" ;;
        W*) wifi="${line#?}" ;;
        D*) date="${line#?}" ;;
        L*) bl="${line#?}" ;;
        V*) vol="${line#?}" ;;
    esac
    xsetroot -name " $vol | $bl | $wifi | $bat | $date "
done < "$pipe"

wait