#!/bin/sh

# ROOT NAME STATUS
# ----------------

# Simple POSIX statusbar script for window managers that use "xsetroot -name"

help='Usage:
- Run the script: $ rnstatus [start/stop/restart]
- Update special modules: $ rnstatus [volume/backlight]'

dir="$HOME/.local/bin/statusbar"
pipe='/tmp/rnstatus-fifo'

. "$dir/rn-modules"

err() {
    printf "ERROR: $1!\n" 1>&2
    exit 1
}

case "$1" in
    volume)
        vol_module > "$pipe" ;;
    backlight)
        . "$dir/rn-modules"
        bl_module > "$pipe" ;;
    help|-h)
        printf "$help\n" ;;
    *)
        [ -p "$pipe" ] || mkfifo "$pipe"

        start_stream() {
            pgrep -x 'rn-stream' 1> /dev/null 2>&1 && err 'Already running' 

            "$dir/rn-stream" "$dir" "$pipe" &
            vol_module > "$pipe" &
            bl_module > "$pipe" &
        }

        stop_stream() {
            pkill --exact 'rn-stream'
        }

        case "$1" in
            stop)
                stop_stream ;;
            start)
                start_stream ;;
            restart)
                stop_stream
                start_stream ;;
            *)
                err 'Invalid argument(s)' ;;
        esac ;;
esac